name: RealTeleporter
main: fr.crafter.tickleman.realteleporter.RealTeleporterPlugin
version: 0.40
website: http://plugins.crafter.fr/tickleman/RealTeleporter/
author: tickleman
depend: [RealPlugin]
commands:
  rt:
    description: RealTeleporter commands
    usage: /<command> help
  rtel:
    description: RealTeleporter commands
    usage: /<command> help
